version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Evera
      MYSQL_USER: Evera_staff
      MYSQL_PASSWORD: senha1234
    volumes:
    - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p=rootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  springapp:
    build: .
    container_name: spring_app
    depends_on:
      mysql:
          condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Evera?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: Evera_staff
      SPRING_DATASOURCE_PASSWORD: senha1234

volumes:
  mysql_data:
