version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Evera
      MYSQL_USER: Evera_staff
      MYSQL_PASSWORD: senha1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
